---
# tasks file for vector-role
- name: Run update
  ansible.builtin.apt:
    update_cache: yes  
- name: Instal curl
  become: true
  ansible.builtin.apt:
    name: 
      - curl
      - sudo
    state: latest
- name: Download distrib vector
  become: true
  get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector-{{ vector_version }}.deb"
    mode: 0755
    timeout: 60
  run_once: True
  register: get_vector
  until: get_vector is succeeded
- name: Install vector deb
  become: true
  ansible.builtin.apt:
    deb: "/tmp/vector-{{ vector_version }}.deb"
    dpkg_options: 'force-confold,force-confdef'
- name: Template it
  become: true
  ansible.builtin.template:
    src: "templates/vector.cfg.j2"
    dest: "{{ vector_home }}"
    backup: True
  register: template_result
  tags: vector_template
